# Generated by Django 4.1 on 2022-12-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='sketchimage',
            name='image',
            field=models.ImageField(null=True, upload_to='sketch_images/'),
        ),
        migrations.AddField(
            model_name='sketchimage',
            name='sketch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sketch'),
        ),
    ]
