# Generated by Django 4.1 on 2023-01-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_profile_sketchimage_image_sketchimage_sketch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='sketch_images/'),
        ),
    ]
